travis:
  secure:
    BINSTAR_TOKEN: sNPawEZqGOFMwQBJ6clOhX16AHB86aucryQXJ2Wf+R+bOnPrMKvPSBe7YAbWupkYk1Av9e9ll8BFH2FnXgYCYc/3UuBqSAOY5B4S1lCAF6FXSvaBWKWqL8F3x1gUmzV2TeY90bjMZy00fegfr+3NfLgp4RNxddVc8OeJIAsSNrJp1J2WuWYpuBwtLcjKwS9vh5fECjAM9am1XfKNdJDewFDP5diA3/d2lWZY5sCWV1tjPfKh/v3kIyyvTExTQWfhdd0dBQ+GlGaxudng4v3hTXdnZTlwsDKBPIRhCBxsy9Im5eZ1zd4UMF9jYyEK6qYSduAZVlFoIgh/Uij/CtxzpWcbCdTz9C8gnGWKLH2d12dkGxW3th74Wdinm5FE4YYeBTXSIcXcsDmO08x4cqQfSAax1vBrtcm5/7Lh6CRwRVTPgUvbqSS9I472X+dnibLJHldKQ4dFC/cdhB5wOuvlq4w1iwUAfWooZ79t0ST5zY46vM3LLVwttoxzY0yEABZFRN5XZusQp/FvqjK8U14dy5t5kFL3CSDV2+FVx7bnS5McV+mpNGywSQBAvzRIfNc9vTe7+YndR/OkWl0aBpPqfb7+02ytrhBYs2crCXovAYWh832IdXYpUZSqHkK0zy3kYfEmhMZKtUZIYCprF1eQIQfau3DFC0Qhk98hyS71u10=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
